name: Go CI and Auto Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Get dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...

      - name: Build
        run: go build -o futil .

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: futil-binary
          path: futil

      - name: Bump version tag
        id: bump_version
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          
          version=${latest_tag#v}
          
          IFS='.' read -r major minor patch <<< "$version"

          patch=$((patch+1))

          new_tag="v$major.$minor.$patch"

          echo "New tag: $new_tag"

          echo "tag=$new_tag" >> $GITHUB_ENV
          
          git tag $new_tag
          git push origin $new_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: futil
          tag_name: ${{ env.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
