name: Go CI and Auto Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Get dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -v ./...

      - name: Build
        run: go build -o futil .

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: futil-binary
          path: futil

      - name: Auto Create GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: futil
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
